### ISSUE TITLE
language selection error in h5peditor.js

### ISSUE THREAD

**Issue by borovinskiy** [h5p/h5p-editor-php-library#157] opened 2022-09-27 17:24 UTC
Branch Scenario have an error when adding Interactive video not for ([english lang]( https://h5p.org/node/1214843)) 

```
Uncaught TypeError: translation[i] is undefined
    updateCommonFieldsDefault https://udoba.org/sites/all/modules/h5p/modules/h5peditor/h5peditor/scripts/h5peditor.js?rgk4nu:280
    updateCommonFieldsDefault https://udoba.org/sites/all/modules/h5p/modules/h5peditor/h5peditor/scripts/h5peditor.js?rgk4nu:278
    updateCommonFieldsDefault https://udoba.org/sites/all/modules/h5p/modules/h5peditor/h5peditor/scripts/h5peditor.js?rgk4nu:278
    success https://udoba.org/sites/all/modules/h5p/modules/h5peditor/h5peditor/scripts/h5peditor.js?rgk4nu:230
    jQuery 6
```

I am found, that in h5peditor.js incorrect check translation (not check translation[i] === undefined) and this can fixed:

```
275c275
<     if (semantics[i].fields !== undefined && semantics[i].fields.length && translation[i] !== undefined &&
---
>     if (semantics[i].fields !== undefined && semantics[i].fields.length &&
280c280
<     if (semantics[i].field !== undefined && translation[i] !== undefined && translation[i].field !== undefined ) {
---
>     if (semantics[i].field !== undefined && translation[i].field !== undefined ) {
```

**Comment by fnoks** [comment] 2022-10-25 11:27
I believe this is a duplicate of https://github.com/h5p/h5p-interactive-video/issues/258

**Closed by fnoks** 2022-10-25 11:27 UTC
